theme = "tokyo-night"
mode = "auto"
vcs = "git"
watch = false
exclude_untracked = false
line_numbers = true
tab_width = 4
wrap_lines = false
menu_bar = true
sidebar = "auto"
agent_notes = true
prompt_save_view_preferences = false
transparent_background = false
