#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
ratio = [1, 2, 5]
sort_by = "mtime"
sort_reverse = true
show_hidden = true

[preview]
max_width = 1200
max_height = 900
image_quality = 60

[opener]
mcat = [
	{ run = "TERM=xterm-kitty mcat --kitty --output interactive %s1", block = true, desc = "View with mcat", for = "unix" },
]

[open]
prepend_rules = [
	{ mime = "image/*", use = [ "mcat", "open" ] },
]
